#!/bin/sh
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
  alias ls='ls --color=auto -F'
  alias v='vim'
else
  alias ls='ls -G'
  alias v='vim'
  alias qplayer='"$QUICK_COCOS2DX_ROOT"/player/bin/mac/quick-x-player.app/Contents/MacOS/quick-x-player'
  # alias mcs='/Applications/Unity/MonoDevelop.app/Contents/Frameworks/Mono.framework/Versions/Current/bin/mcs'
  # alias mono='/Applications/Unity/MonoDevelop.app/Contents/Frameworks/Mono.framework/Versions/Current/bin/mono'
  export PATH=$PATH:/Applications/Unity/MonoDevelop.app/Contents/Frameworks/Mono.framework/Versions/Current/bin
fi

if command -v ack-grep > /dev/null; then
    alias ack=ack-grep
fi

alias translate='dict'
alias google='sr -browser=w3m google'
alias rm='rm -i'
alias l='ls -l -S -h'
alias ll='ls -l -S -h'
alias gs='git status'
alias tmux='tmux -2'
alias pss='ps -ef|grep'
alias vv='env|grep'
alias vnc="vncviewer -FullColor=0 -LowColorLevel=2 192.168.1.110"
alias fixjsstyle="fixjsstyle --nojsdoc --ignore_errors 1,131"
alias g='git'
alias serve='python -m SimpleHTTPServer'
alias pyqt='ipython qtconsole --pylab=inline --colors=linux'
alias pip='pip --trusted-host pypi.douban.com'
PATH=/opt/eclipse:/opt/google-appengine:~/config/bin:$PATH
PYTHONPATH=/home/gl/projects/clevercss3/:$PYTHONPATH
export HAXE_LIBRARY_PATH=/opt/haxe/std
export EDITOR=vim
